### ISSUE TITLE
Raise exception if graveyard is not found

### ISSUE THREAD

**Issue by pshriwise** [svalinn/DAGMC-viz#19]
Right now the `remove_graveyard` function will print a warning if a graveyard cannot be found in the specified file and call `exit()`. Now that this function is called outside of the `GraveIdentifyAndRemove.py` module, we should probably raise an exception here. 

This behavior currently forces users to provide a `.h5m` geometry with a graveyard to the `DataLoading.py` script. After updating the `remove_graveyard` function, the call to `remove_graveyard` should catch that exception and move on if no graveyard is found in the geometry file.

**Comment by pshriwise** [comment]
@piperlincoln you mentioned yesterday that we'd be handling this exception in two places and ignoring it in both... I'm wondering if we shouldn't just print the warning and not throw an exception at all. 

Another, perhaps ideal, option would be to separate identification of the graveyard entityset from its removal. This refactor would create a new function (let's call it `find_graveyard`) may raise an exception or return `None` if no graveyard is found. This would provide a nice way to check a geometry for a graveyard without removing it in the future. Also, we could handle the result of that function in `remove_graveyard` and not have to change any external code. 

What do you think?

**Comment by piperlincoln** [comment]
@pshriwise Regarding your first comment, not throwing the exception would mean an unnecessary file is written on the user's computer due to the fact that the file they passed in would already not contain a graveyard! Regarding your second comment, I agree that that is the ideal option and I will start working on refactoring my code to do so!

**Comment by piperlincoln** [comment]
NOTE: It was decided that due to the fact that external code would have to be altered if `find_graveyard` was added, and there likely would not be a case in which a user would want to identify the graveyard and then decide not to remove it, I moved forward with the cleaner option of raising an exception in `remove_graveyard` if a graveyard is not found, and catching it in `DataLoading.py`.

**Comment by piperlincoln** [comment]
Addressed in PR #23
